parameters:
#    ieps_back_office.example.class: Ieps\BackOfficeBundle\Example

services:
#    ieps_back_office.example:
#        class: %ieps_back_office.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
