ieps_back_office:
    resource: "@IepsBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /

ieps_paypal:
    resource: "@IepsPaypalBundle/Resources/config/routing.yml"
    prefix:   /

ieps_cms_base:
    resource: "@IepsCmsBaseBundle/Resources/config/routing.yml"
    prefix:   /



