ieps_back_office:
    resource: "@IepsBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /

ieps_paypal:
    resource: "@IepsPaypalBundle/Resources/config/routing.yml"
    prefix:   /

ieps_cms_base:
    resource: "@IepsCmsBaseBundle/Resources/config/routing.yml"
    prefix:   /

#login:
#    pattern:   /login
#    defaults:  { _controller: IepsUserBundle:Security:login }

#login_check:
#    pattern:   /login_check

#logout:
#    pattern:   /logout

