parameters:
#    ieps_user.example.class: Ieps\UserBundle\Example

services:
#    ieps_user.example:
#        class: %ieps_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
