parameters:
#    ieps_cms_base.example.class: Ieps\CmsBaseBundle\Example

services:
#    ieps_cms_base.example:
#        class: %ieps_cms_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
