parameters:
#    gce_news.example.class: GCE\NewsBundle\Example

services:
#    gce_news.example:
#        class: %gce_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
