#ieps_paypal_payment:
#    pattern:  /payments
#    defaults: { _controller: IepsPaypalBundle:Default:... }
    

#ieps_paypal_payment_details:
#    pattern:  /{id}/details
#    defaults: { _controller: IepsPaypalBundle:Default:... }