parameters:
#    ieps_paypal.example.class: Ieps\PaypalBundle\Example

services:
#    ieps_paypal.example:
#        class: %ieps_paypal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
